name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        id: go
        with:
          go-version: '1.14.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: $HOME/src/github.com/dash-app/remote-go
      - name: "Test aircon"
        env:
          GOPATH: /home/runner/work/
        run: go test -bench -benchmem -v ./aircon/...
