name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.3'
      - uses: actions/checkout@v2
      - name: "Ensure library"
        run: go get -u -v ./...
      - name: "Test aircon"
        run: go test -bench -benchmem -v ./aircon/...
